### ISSUE TITLE
Can't compile asynchbase sub project.

### ISSUE THREAD

**Issue by babokim** [kakao/s2graph#1]
I have compiled asynchbase according to the README file. But I found the following "make" error message and mvn error messages. 

```
[~/s2graph]# cd asynchbase; make; mvn install
Makefile:29: third_party/include.mk: No such file or directory
make: *** No rule to make target `third_party/include.mk'.  Stop.
.....
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/babokim/work/workspace/s2graph/asynchbase/test/TestNSREs.java:[94,23] error: cannot find symbol
[ERROR]   symbol:   class KeyValue
  location: class TestNSREs
/Users/babokim/work/workspace/s2graph/asynchbase/test/TestNSREs.java:[95,23] error: cannot find symbol
[ERROR]   symbol:   class RegionInfo
  location: class TestNSREs
/Users/babokim/work/workspace/s2graph/asynchbase/test/TestNSREs.java:[96,23] error: cannot find symbol
```

**Comment by SteamShon** [comment]
missed few include.mk files under third_party. 
also instread of make, try with make pom.xml then mvn install. also updated readme for this.
now try to install asynchbase again then if any error comesup, then let me know~

**Comment by SteamShon** [comment]
turns out issues comes from directory structure is different what maven expect like @babokim mentioned.

it turns out I missed to add two files(https://github.com/daumkakao/s2graph/commit/c4ac88c3ba99c115341fff981dcd0184105065de)

after this, I could successfully install asynchbase.

**Comment by babokim** [comment]
@SteamShon, thanks. 
After applying the patch, I can compile.
