### ISSUE TITLE
Vagrant dev environment

### ISSUE THREAD

**Issue by HyunsungJo** [kakao/s2graph#107]
Setting up S2Graph on your local machine is still quite a hassle. (Although much has improved since a couple of months ago..)

[Vagrant](https://docs.vagrantup.com/v2/why-vagrant/) seems like a nice approach to this problem.

"Vagrant will isolate dependencies and their configuration within a single disposable, consistent environment, without sacrificing any of the tools you're used to working with (editors, browsers, debuggers, etc.)."

**Comment by SteamShon** [comment]
@mojo22jojo I merged this into develop. soon will be merged to master. check this on develop and close it if all works fine.

**Comment by SteamShon** [comment]
@mojo22jojo can you also update Getting started page on documentation?

**Comment by HyunsungJo** [comment]
Sure.
- Comando

**Comment by HyunsungJo** [comment]
@SteamShon 
1. I made an S2Graph [Vagrant base box](https://atlas.hashicorp.com/s2graph/boxes/base-box) and reduced boot time. #123 
2. Revised README.md according to the latest version. #122

**Comment by HyunsungJo** [comment]
Also revised GitBook in branch [quick-start-with-vagrant](https://www.gitbook.com/book/steamshon/s2graph-book/edit#/edit/quick-start-with-vagrant/getting_started.md)!

**Comment by daewon** [comment]
:+1: it works
