### ISSUE TITLE
Provide orderBy query option for sorting results by edge's property

### ISSUE THREAD

**Issue by hsleep** [kakao/s2graph#158]
The results of getEdge operation always is sorted by the score and the timestamp descending order.
If provide `orderBy` query option like `groupBy` option, client can determine query result's sorting order.

I suggest the query like below form.

``` js
{
  "orderBy": [
    {"score": "DESC"},
    {"timestamp": "ASC"}
  ],
  ...
}
```

**Comment by SteamShon** [comment]
@hsleep would be nice feature~! looking forward PR.
