### ISSUE TITLE
QueryResult And QueryRequest refactoring

### ISSUE THREAD

**Issue by SteamShon** [kakao/s2graph#179]
Currently QueryResult class contains Query, StepIndex, QueryParam and sequence of EdgeWithScore class. This make implementation easy but it is does not make sense that QueryResult. QueryRequest is also exist but these two classes have same data. 

I think it would be better to split data for request to QueryRequest and only result data to QueryResult.

**Comment by SteamShon** [comment]
2edeaf9648220efc784e424b1c549a34b417885e resolving following.
- QueryResult

Before: contains following data.
Query, stepIdx, queryParam, Seq[EdgeWithScore], timestamp

After: represent edge and score and when this result built.
Seq[EdgeWithScore], timestamp
- QueryRequest

before: 
Query, stepIdx, vertex, queryParam, prevStepScore, isInnerCall, parentEdges

after: only contains following.
Query, stepIdx, vertex, QueryParam

**Comment by daewon** [comment]
:+1:
