### ISSUE TITLE
Request Cache for Super Node

### ISSUE THREAD

**Issue by SteamShon** [kakao/s2graph#183]
I want to ask about feasibility of following idea.
## Problem

let me first start with one example usage, realtime collaborative filtering.

for example, in below picture, user-content activity is represented by top layer and content-content similarity is represented by bottom layer, so it is basically two step query such as V("user") -> interactedContents -> similarContents

<img width="734" alt="screen shot 2015-11-27 at 7 53 31 am" src="https://cloud.githubusercontent.com/assets/1264825/11431473/fbcee25a-94db-11e5-90df-c88a36848716.png">

current problem is that there are too much request amplification on content-content similarity layer(second step).

Many times, content interaction is very skewed and only few of them(few most popular contents) consist of most of user`s interaction which means many user will ask what are similar content of these few most popular contents.(watch red arc on picture).

This problem is not limited to realtime collaborative filtering example. In general, It is inevitable to amplify request on next step if there is super node(few of most popular content in example) on previous step (super node also could be very famous people in social media domain). 

super node eat up all resource on HBase side even though we use bloomfilter. 

here is example table that has very small amount of data(2~3 MB) per each region, but requests on this table reached over 400K per second.

<img width="670" alt="screen shot 2015-11-27 at 8 36 23 am" src="https://cloud.githubusercontent.com/assets/1264825/11431757/00bee4f8-94e2-11e5-8f28-087cc727f18f.png">
## Approach

I have been experimenting with following two approach.
### Simple Result Cache

current implementation already use local cache on meta data from RDBMS. so why not use local cache for result? 

well, it turns out local cache is only useful when data is very small and can be fitted into memory. 
so tried with Redis cluster as cache. I used [Rediscala](https://github.com/etaty/rediscala) client since it support asynchronous client. 

<img width="1091" alt="screen shot 2015-11-27 at 8 09 35 am" src="https://cloud.githubusercontent.com/assets/1264825/11431560/4328ceac-94de-11e5-9f65-8ada13ad3d55.png">

summary is following.
1. we can reduce requests into HBase if we use redis. but how we going to reduce requests into redis then?
2. simply not performant enough. the response time drops because we spend all our cpu for sending rpcs into redis. have used pipelined but not helped much.

So basically, we need to reduce number of rpc calls to what ever storage is(HBase or redis or whatever cache layer) rather than optimize single rpc performance.
### Future Cache

I researched and find out [spray cache](http://spray.io/documentation/1.2.3/spray-caching/) idea can be nice solution for our problem.

Basic idea is storing Future for expensive operation, not result of expensive operation.

By storing Future instead result, we can save lots of resource thanks to future`s callback property.

![screen shot 2015-11-27 at 12 18 36 pm](https://cloud.githubusercontent.com/assets/1264825/11433475/1045debc-9501-11e5-95d2-a4a37c38f905.png)

spray cache it self is very nice library but to understanding mechanism, I tried to implemented it by hand.

current implementation expire future on two criteria.
1. number of concurrent request on same key while single future is running.
2. expire time for future after accessed.

This criteria means "squash maximum concurrent request to storage into one future, or squash at least expire time.

experiment shows that there is throuhput gain and reduce on reponse time with much smaller requests sent to HBase.

will try more experiment on this.
## Discussion

Is this right? What others think? How we are going to our problem? 
give me a direction and I am on my way to experiment more. any feedback would be appreciated and correct me if I am on wrong direction.

**Comment by HeartSaVioR** [comment]
Second approach looks promising. 
One thing to consider is when we want to invalidate cache element.
Do you want to remove future from cache table as soon as future gets the result? Or do you want to store result for some moment? 
If you want to do latter, do you want to tolerate showing previous data for some moment, or invalidate cache immediately when result becomes invalid (removed, updated)? If operation is async, it seems that invalidating cache still have a chance to show previous data.

**Comment by SteamShon** [comment]
@HeartSaVioR 

good point. so problem is when to invalidate future cache table. right.

if we use second approach on every request, then there is chance to show previous data since. 

I was thinking about giving user option to specify, "ok I am ok with this much of time old data" then run second approach only when user specify this option. This option can be turn on by providing cacheTTL on query. if user specify this value, then we can expire future from cache after this time. but if first request put future on table, then there is no more request on that key, then we need to expiration. so I was thinking about max idle time too.

The basic expiration policy is when future finished, then remove it from future table(like you said).

I want to give option to user to control this by # of concurrent request on same key while first future finished(1 is same as you described).

so in brief, followings are what I have come up with.
1. # of concurrent request on future table.
2. time to live
3. time to idle

I am testing with these 3 and let me know if you come up with better way.

**Comment by HeartSaVioR** [comment]
@SteamShon 
2, 3 are clear and make sense to me.
Regarding 1, I'm curious about use cases of this approach. Basic expiration policy could be also  implemented via setting TTL to 0, so we may want to get another use cases.

**Comment by SteamShon** [comment]
This is what I have found sofar.

I tested with following data + query.

## test graph data

for quick test I used following synthetic data.

matrix: 1000000 x 1
rowId: 0 ~ 1000000 
colId: one of randInt(0, 1000000)

## query

ids array size 100. each test set represent probability of future cache hit.

```
{
    "srcVertices": [
        {
            "serviceName": "s2graph-test",
            "columnName": "item_id_test",
            "ids": [
                %s
            ]
        }
    ],
    "steps": [
        {
            "step": [
                {
                    "cacheTTL": -1,
                    "label": "insert_test",
                    "direction": "out",
                    "offset": 0,
                    "limit": 1
                }
            ]
        }
    ]
}
```

## test

I was curious about how much future cache can reduce requests to hbase, when the probability to hit future cache decrease.

so start from 100% hit to almost 0% hit, I created following test sets. for each case, I compared # of requests to hbase with respose time and throughput on s2graph server to see how much penalty we get on client side. 

### test set 1:  100 from randInt(0, 100) per each query request

this is 100% hit case.

#### HBase

turns out by increasing cacheTTL, we can reduce significant requests to hbase as expected.

##### no cache

<img width="1244" alt="id 100 _hbase_cachttl_-1" src="https://cloud.githubusercontent.com/assets/1264825/11478582/3d6f02c4-97d1-11e5-94ab-10f97f6a0cfd.png">

##### cacheTTL 1000

<img width="1218" alt="id 100 _hbase_cachett_1000" src="https://cloud.githubusercontent.com/assets/1264825/11478594/4f411b86-97d1-11e5-9c45-70eda7199f9d.png">

##### cacheTTL 10000

<img width="1206" alt="id 100 _hbase_cachettl_10000" src="https://cloud.githubusercontent.com/assets/1264825/11478610/5cdf28fa-97d1-11e5-8c41-e8895668c4a4.png">

#### App server

turns out when future cache hit with high probability, client response and throughput increase also as expected. 

##### no cache

<img width="1020" alt="id 100 _app_cachettl_-1" src="https://cloud.githubusercontent.com/assets/1264825/11478643/9f627c9a-97d1-11e5-873f-12464d6cb692.png">

##### cacheTTL 1000

<img width="1022" alt="id 100 _app_cachettl_1000" src="https://cloud.githubusercontent.com/assets/1264825/11478650/a99333e4-97d1-11e5-9780-f80138a92c77.png">

##### cacheTTL 10000

<img width="1043" alt="id 100 _app_cachettl_10000" src="https://cloud.githubusercontent.com/assets/1264825/11478654/b3afbaaa-97d1-11e5-9b03-f1b371903b50.png">

### test set 2: 100 from randInt(0, 1000) per each query request

less hit than set 1 but still very high probability of hit.

#### HBase

##### no cache

<img width="1209" alt="id 1000 _hbase_cachettl_-1" src="https://cloud.githubusercontent.com/assets/1264825/11478688/dcc8caa8-97d1-11e5-806d-dfe08bcfe772.png">

##### cacheTTL 1000

<img width="1267" alt="id 1000 _hbase_cachettl_1000" src="https://cloud.githubusercontent.com/assets/1264825/11478698/e5f3bd54-97d1-11e5-89cd-a54962910e69.png">

##### cacheTTL 10000

<img width="1205" alt="id 1000 _hbase_cachettl_10000" src="https://cloud.githubusercontent.com/assets/1264825/11478713/ef973a52-97d1-11e5-8fc8-c93c72b67371.png">

#### App server

##### no cache

<img width="1007" alt="id 1000 _app_cachettl_-1" src="https://cloud.githubusercontent.com/assets/1264825/11478736/101d4f32-97d2-11e5-811c-ecf2a1af52ad.png">

##### cacheTTL 1000

<img width="1015" alt="id 1000 _app_cachettl_1000" src="https://cloud.githubusercontent.com/assets/1264825/11478743/1867ee18-97d2-11e5-9539-5f586fc02ecd.png">

##### cacheTTL 10000

<img width="1002" alt="id 1000 _app_cachettl_10000" src="https://cloud.githubusercontent.com/assets/1264825/11478750/1fcc82cc-97d2-11e5-8a8f-da3f1b3359e3.png">

### test set 3: 100 from randInt(0, 10000) per each query request

less hit than set 1 but still high probability of hit.

#### HBase

##### no cache

<img width="1248" alt="id 10000 _hbase_cachettl_-1" src="https://cloud.githubusercontent.com/assets/1264825/11478776/3f62394c-97d2-11e5-8c97-68bd12114cf5.png">

##### cacheTTL 1000

<img width="1217" alt="id 10000 _hbase_cachettl_1000" src="https://cloud.githubusercontent.com/assets/1264825/11478788/48d4dc82-97d2-11e5-8759-7635ac003ca7.png">

#### App server

##### no cache

<img width="997" alt="id 10000 _app_cachettl_-1" src="https://cloud.githubusercontent.com/assets/1264825/11478797/56fab0b6-97d2-11e5-8003-744f7fa4de5c.png">

##### cacheTTL 1000

<img width="986" alt="id 10000 _app_cachettl_1000" src="https://cloud.githubusercontent.com/assets/1264825/11478803/5e25e6f8-97d2-11e5-9058-34a2f97f032c.png">

### test set 4: 100 from randInt(0, 100000) per each query request

small probability of hit.

#### HBase

##### no cache

<img width="1246" alt="id 100000 _hbase_cachettl_-1" src="https://cloud.githubusercontent.com/assets/1264825/11478831/77282166-97d2-11e5-82af-df67fafca01b.png">

##### cacheTTL 1000

<img width="1220" alt="id 100000 _hbase_cachettl_1000" src="https://cloud.githubusercontent.com/assets/1264825/11478835/7c4215e4-97d2-11e5-9dc0-5fb2817d0f44.png">

##### cacheTTL 10000

<img width="1204" alt="id 100000 _hbase_cachettl_10000" src="https://cloud.githubusercontent.com/assets/1264825/11478837/8161e888-97d2-11e5-8bd6-a697c53d10f6.png">

#### App server

##### no cache

<img width="987" alt="id 100000 _app_cachettl_-1" src="https://cloud.githubusercontent.com/assets/1264825/11478858/9337f2f0-97d2-11e5-8c29-c89acbd04e86.png">

##### cacheTTL 1000

<img width="992" alt="id 100000 _app_cachettl_1000" src="https://cloud.githubusercontent.com/assets/1264825/11478863/98d87f7c-97d2-11e5-8cff-c1f734564f6d.png">

##### cacheTTL 10000

<img width="994" alt="id 100000 _app_cachettl_10000" src="https://cloud.githubusercontent.com/assets/1264825/11478881/9f92845c-97d2-11e5-88f3-012ba67e1637.png">

### test set 5: 100 from randInt(0, 1000000) per each query request

very small hit. I tested with long cacheTTL this case to see if rlu eviction is working correctly(not blowing up memory)

#### HBase

##### no cache

<img width="1239" alt="id 1000000 _hbase_cachettl_-1" src="https://cloud.githubusercontent.com/assets/1264825/11478908/bdd433d4-97d2-11e5-9697-fc15950ec13f.png">

##### cacheTTL 1000

<img width="1206" alt="id 1000000 _hbase_cachttl_1000" src="https://cloud.githubusercontent.com/assets/1264825/11478917/c5ebbf74-97d2-11e5-9406-2535c6a5d899.png">

##### cacheTTL 10000

<img width="1248" alt="id 1000000 _hbase_cachettl_10000" src="https://cloud.githubusercontent.com/assets/1264825/11478925/cf220eea-97d2-11e5-9558-70bda620efa7.png">

##### cacheTTL 100000

<img width="1270" alt="id 1000000 _hbase_cachettl_100000" src="https://cloud.githubusercontent.com/assets/1264825/11479119/ad560090-97d3-11e5-98e3-a638212e4036.png">

#### App server

##### no cache

<img width="990" alt="id 1000000 _app_cachettl_-1" src="https://cloud.githubusercontent.com/assets/1264825/11478996/2f54c334-97d3-11e5-8f31-62d9a3703a9a.png">

##### cacheTTL 1000

<img width="999" alt="id 1000000 _app_cachettl_1000" src="https://cloud.githubusercontent.com/assets/1264825/11478999/34a5da44-97d3-11e5-9c5a-e90f8c1842f9.png">

##### cacheTTL 10000

<img width="1003" alt="id 1000000 _app_cachettl_10000" src="https://cloud.githubusercontent.com/assets/1264825/11479003/39883084-97d3-11e5-95bb-0c78774d0c9f.png">

##### cacheTTL 100000

<img width="1006" alt="id 1000000 _app_cachettl_100000" src="https://cloud.githubusercontent.com/assets/1264825/11479011/3ea36890-97d3-11e5-972d-cd424f9767f1.png">

## Result

If there are high probability of future cache hit, then great, we can reduce number of requests to storage as we expected and actually getting performance gain. if there is no chance to hit on future cache, then simply don`t use this feature by specifying cacheTTL -1 to avoid wasting cpu cycle to look for cache table.

**Comment by SteamShon** [comment]
@HeartSaVioR 

I agree that there is no real use cases for # of cuncurrent requests on same future. I was curious how performance affected if we cache more requests into future cache so 1 was just for test purpose.

So finally I was testing above result with following setup.

cache is simple LRU without expiration on it and each query hint cacheTTL specifying how much old data user can accept so each future can have different expiration time.

if request on cached future keep comming, then expire if current time > cachedAt + query`s cacheTTL.
otherwise let LRU evit this not accessed future. 

Thanks for pointing out and let me know what you think.

**Comment by Ephemera** [comment]
:+1:

**Comment by HeartSaVioR** [comment]
@SteamShon :+1:
Since issue points out about super node, which represents that we expect cache hit would be high when circumstance is normal.
Actually test 5's TPS is much lower than test 1 without cache, so we could think it is worst case and tolerate result of test 5.

**Comment by elric-k** [comment]
:+1:

**Comment by djfwan** [comment]
:+1:
