### ISSUE TITLE
Bucket model is not updated after cache TTL time.

### ISSUE THREAD

**Issue by hsleep** [kakao/s2graph#187]
`Experiment` model has a `Bucket` list as a **value**. So, `Bucket` list in `Experiment` is not updated even if cache TTL time passed.
When `Bucket` is changed in DB,  `SafeUpdateCache` returns the old `Bucket` to initialize `Experiment`. So, `Experiment` is updated but `Bucket` is not. After 2*TTL time elapsed, `Bucket` list in `Experiment` is updated successfully.

**Comment by daewon** [comment]
@hsleep :+1:
