### ISSUE TITLE
Can't compile asyncbase with Java8 or Protobuf 260

### ISSUE THREAD

**Issue by daewon** [kakao/s2graph#2]
It works with Java7, Protobuf 250, but error occurred with
Java 8 Or Protobuf 261

I can't find prerequisites versions (java7, protobuf250) on README.md

Error messages.

```
../../asynchbase/target/generated-sources/protobuf/java/org/hbase/async/generated/ClientPB.java:[139,30] error: cannot find symbol
[ERROR]   symbol:   class ProtocolStringList
```

**Comment by wishoping** [comment]
Protobuf version 2.4.1 version doesn't also generate java classes from PB files( in asynchbase/protobuf/*.proto).

If you have `cannot find symbol something` error when `mvn install`, you need to make sure your protocol buffer version as 2.5.0!

**Comment by SteamShon** [comment]
update protobuf version to 2.6.1 as we change our default hbase version to apache 1.0.1. 
I forgot to reference this issue on PR but you can checkout https://github.com/daumkakao/s2graph/pull/6.
can u pull then re-try this again and check if it work?

**Comment by daewon** [comment]
it's works!
after pull, compile success with protobuf 261 with java7
