### ISSUE TITLE
A link of route file is not found.

### ISSUE THREAD

**Issue by qwefgh90** [kakao/s2graph#24]
https://github.com/daumkakao/s2graph#rest-api-glossary

I can't browse the **routes file** in above link. It is connected with [this link](https://github.com/daumkakao/s2graph/blob/master/res/conf/routes).

didn't a link change from old to https://github.com/daumkakao/s2graph/blob/master/conf/routes?

**Comment by SteamShon** [comment]
@qwefgh90 

fixed broken link for routes.
