### ISSUE TITLE
provide A/B test ability.

### ISSUE THREAD

**Issue by SteamShon** [kakao/s2graph#32]
In daumkakao, lots of services use s2graph as recommendation engine.

for recommendation usage, it is important to redirect traffic to multiple logic then provide way for user to distinguish each logic so they can measure click-through-rate on each logic(and decide which is better).

I think it is better to seperate A/B test ability(exactly, redirect traffic to multiple logic) to other project for long term, but for now, it is embedded in s2graph rest project. 

It would be better to generalize A/B test ability more and provide seperate project so others who don`t want to use s2graph but interested in traffic redirection can use.

**Comment by wishoping** [comment]
:+1:
