### ISSUE TITLE
Wrong timestamp format in README example.

### ISSUE THREAD

**Issue by babokim** [kakao/s2graph#7]
I tested with HBase 0.98.12-hadoop2 and called the following command which is from README:

```
curl -XPOST localhost:9000/graphs/edges/insert -H 'Content-Type: Application/json' -d '
[
  {"from":1,"to":101,"label":"graph_test","props":{"time":-1, "weight":10},"timestamp":1417616431},
  {"from":1,"to":102,"label":"graph_test","props":{"time":0, "weight":11},"timestamp":1417616431},
  {"from":1,"to":103,"label":"graph_test","props":{"time":1, "weight":12},"timestamp":1417616431},
  {"from":1,"to":104,"label":"graph_test","props":{"time":-2, "weight":1},"timestamp":1417616431}
]
'
```

I received a success message "1 insert success" but I could not find any rows in the HBase table. 
I researched this cause and found that timestamp format in the example is wrong format. 
["timestamp":1417616431] value is not a Java timestamp format. After changing to Java timestamp format, s2graph stored several rows in the HBase table.
README file should be changed or verifying logic for timestamp should be added.

**Comment by daewon** [comment]
@mojo22jojo fix example timestamp format read https://steamshon.gitbooks.io/s2graph-book/content/
:+1:
